# ======================================================
# Get's node image with the production deps
# ======================================================
FROM node:12-alpine AS deps
WORKDIR /app
COPY package.json ./
RUN npm install

# ======================================================
# Builds the final image from the previous two
# ======================================================
FROM node:12-alpine
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules/
COPY ./src/ ./
RUN npm install -g nodemon
CMD [ "node", "index.js" ]
EXPOSE 8000
