version: '2.4'

services:
  # The Apollo service
  apollo:
    image: ${APOLLO_CONTAINER_IMAGE}
    build:
      context: ./apollo
      dockerfile: Dockerfile
    command: sh -c "yarn global add nodemon && nodemon -v && NODE_ENV=development nodemon -V -L src/index.js"
    cpus: '0.25'
    mem_limit: 250M
    volumes:
      - ./apollo/src:/app/src:delegated
      - ./apollo/schema:/app/schema:delegated
    ports:
      - '${APOLLO_LISTEN_PORT:-8000}:${APOLLO_LISTEN_PORT:-8000}'
    environment:
      # The port for Apollo to listen to
      PORT: '${APOLLO_LISTEN_PORT:-8000}'

      # The path for the Apollo GraphQL API
      GRAPHQL_API_PATH: ${APOLLO_API_PATH:-/api/graphql}

      JWKS_URI: ${JWKS_URI:?You must specify JWKS_URI}
      JWT_ISSUER: ${JWT_ISSUER:?You must specify JWT_ISSUER}

      PRISMA_ENDPOINT: http://prisma:${PRISMA_LISTEN_PORT:-7000}
      PRISMA_SECRET: ${PRISMA_SECRET:?You must specify PRISMA_SECRET}

      LOG_LEVEL: ${LOG_LEVEL:-debug}

      # OAUTH_TOKEN_ENDPOINT: ${OAUTH_TOKEN_ENDPOINT:?You must specify OAUTH_TOKEN_ENDPOINT}
      # OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID:?You must specify OAUTH_CLIENT_ID}

      # == Mission Control Specific Environment Variables ==
      SENDGRID_API_KEY: ${SENDGRID_API_KEY:?You must specify SENDGRID_API_KEY}

      CODE_CLIMATE_API: ${CODE_CLIMATE_API:?You must specify CODE_CLIMATE_API}
      CODE_CLIMATE_TOKEN: ${CODE_CLIMATE_TOKEN:?You must specify CODE_CLIMATE_TOKEN}

      GIT_HUB_API: ${GIT_HUB_API:?You must specify GIT_HUB_API}
      GIT_HUB_TOKEN: ${GIT_HUB_TOKEN:?You must specify GIT_HUB_TOKEN}

  # The Prisma service
  prisma:
    image: prismagraphql/prisma:1.34
    cpus: '0.25'
    mem_limit: 250M
    ports:
      - '${PRISMA_LISTEN_PORT:-7000}:${PRISMA_LISTEN_PORT:-7000}'
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_LISTEN_PORT:-7000}
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET:?You must specify PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: ${POSTGRES_USER:-prisma}
            password: ${POSTGRES_PASSWORD:-prisma}

  # The Postgres service
  postgres:
    image: postgres:10.3
    cpus: '0.25'
    mem_limit: 250M
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-prisma}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-prisma}
    volumes:
      - postgres:/var/lib/postgresql-prisma/data:delegated

volumes:
  postgres: ~
