name: Test Coverage

# Coverage only counts against master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  coverage:
    name: Runs tests publish test coverage to Code Climate

    runs-on: ubuntu-latest

		# The steps for the job, executed in sequence
    steps:
			# A GitHub action for checking out the current branch
      - uses: actions/checkout@master

			# A GitHub action to setup Node.js
      - uses: actions/setup-node@master
        with:
          node-version: "12"

			# A GitHub action for running tests and publishing coverage
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
					# An environment variable, the value is stored as a GitHub repo secret
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
        with:
					# Run the coverage target in the Makefile
          coverageCommand: make coverage

					coverageLocations: ["./apollo/coverage/clover.xml:clover", "./prisma/coverage/clover.xml:clover"]

          debug: true
